[Issue-21] Esquema lógico e físico - tabelas Verba, Conteudo e Integr…
LorhanSohaky/LabBD pull request #29
Opened 2019-06-18 20:43 UTC by rmmorimoto

Esquema lógico dentro do logico.txt já existente, esquema físico em arquivo sql separado para evitar conflitos.

2019-06-18 22:21 UTC, jonathangouvea requested changes
O atributo data_verba está como NUMBER, mas seria melhor estar como DATE (ou TEXT, mas para seguir o padrão DATE é o melhor)

2019-06-18 22:39 UTC, LorhanSohaky commented
Resolvi o conflito no `logico.txt`. Não vejo problema em colocar o arquivo sql no mesmo arquivo

2019-06-18 22:46 UTC, LorhanSohaky requested changes

2019-06-18 22:46 UTC, LorhanSohaky commented on modelo_fisico/logico.txt
> +verba(PK(FK_alteracao(data), FK_atividade_extensao(nro_extensao), FK_coordenador(id_pessoa)), valor, destino, origem);
Creio que as chaves sejam as mesmas da Entidade Alteração e como Alteração é uma entidade fraca, depende das chaves coordenador e atividade de extensão. O mesmo vale para as entidades Conteúdo e Integrante

2019-06-18 22:46 UTC, LorhanSohaky commented on modelo_fisico/logico.txt
> +verba(PK(FK_alteracao(data), FK_atividade_extensao(nro_extensao), FK_coordenador(id_pessoa)), valor, destino, origem);
Pode dar uma olhada no #27 para ver como estão as chaves

2019-06-19 00:02 UTC, jonathangouvea approved these changes

2019-06-19 01:39 UTC, jessica-antunes-vindi approved these changes

2019-06-19 02:07 UTC, closed without merging

2019-06-19 02:07 UTC, LorhanSohaky approved these changes